- name: Install Utility software
  apt: name={{item}} state=latest update_cache=yes
  loop: [ 'software-properties-common' , 'python-mysqldb' ]

- name: Install MariaDB Packages
  apt: name={{item}} state=latest update_cache=yes
  loop: [ 'mariadb-client' , 'mariadb-common' , 'mariadb-server' ]
    
- name: Create MariaDB Directories
  file: path=/data/{{item}} state=directory owner=mysql group=mysql recurse=yes
  loop: [ 'db' , 'log' ]

- name: Count files in /data/db
  find: path=/data/db patterns='*'
  register: db_files

- name: Run mysql_install_db only if /data/db is empty
  command: mysql_install_db --datadir=/data/db
  when: db_files.matched|int == 0

- name: Start MariaDB
  service: name=mysql state=started

- name: Is root password set?
  command: mysql -u root --execute "SELECT NOW()"
  register: is_root_password_set
  ignore_errors: yes

- name: Delete anonymous users
  mysql_user: user="" state="absent"
  when: is_root_password_set.rc == 0

- name: Generate mysql root password
  shell: tr -d -c "a-zA-Z0-9" < /dev/urandom | head -c 10
  register: mysql_root_password
  when: is_root_password_set.rc == 0

- name: Set root password
  mysql_user: user=root password="{{ mysql_admin_password }}" host=localhost
  when: is_root_password_set.rc == 0

- name: Set root password for other hosts
  mysql_user: user=root password="{{ mysql_admin_password }}" host="{{item}}" login_user="root" login_host="localhost" login_password="{{ mysql_admin_password }}"
  when: is_root_password_set.rc == 0
  loop: [ "127.0.0.1" , "::1" , "localhost" ]
