---
- name: Ensure dirmngr is installed (gnupg dependency).
  apt: name={{ item }} state=latest update_cache=yes
  loop: [ 'dirmngr', 'ssh', 'python3-setuptools', 'python3-pip', 'virtualenv' ]

- name: Add ansible repository.
  apt_repository: repo='ppa:ansible/ansible'

- name: Update apt cache.
  apt: update_cache=true cache_valid_time=86400

- name: Install Ansible.
  apt:
    name: ansible
    state: latest
